### ISSUE TITLE
Error installing on 64-bit Linux system, RHEL

### ISSUE THREAD

**Issue by jikku** [jdorner/node-sapnwrfc#14]
I tried an npm install on a 64-bit Linux machine running RHEL 5.5 with node 0.12.7 installed and I get an error:

> sapnwrfc@0.1.5 install /root/SAPConnector/node_modules/sapnwrfc
> node preinstall.js

child_process: customFds option is deprecated, use stdio instead.
{ [Error: Could not load the bindings file. Tried:
 -> /root/SAPConnector/node_modules/sapnwrfc/build/Debug/sapnwrfc.node
 -> /root/SAPConnector/node_modules/sapnwrfc/build/Release/sapnwrfc.node
 -> /root/SAPConnector/node_modules/sapnwrfc/out/Debug/sapnwrfc.node
 -> /root/SAPConnector/node_modules/sapnwrfc/Debug/sapnwrfc.node
 -> /root/SAPConnector/node_modules/sapnwrfc/out/Release/sapnwrfc.node
 -> /root/SAPConnector/node_modules/sapnwrfc/Release/sapnwrfc.node
 -> /root/SAPConnector/node_modules/sapnwrfc/build/default/sapnwrfc.node
 -> /root/SAPConnector/node_modules/sapnwrfc/compiled/0.12/linux/x64/sapnwrfc.node]
  tries:
   [ '/root/SAPConnector/node_modules/sapnwrfc/build/Debug/sapnwrfc.node',
     '/root/SAPConnector/node_modules/sapnwrfc/build/Release/sapnwrfc.node',
     '/root/SAPConnector/node_modules/sapnwrfc/out/Debug/sapnwrfc.node',
     '/root/SAPConnector/node_modules/sapnwrfc/Debug/sapnwrfc.node',
     '/root/SAPConnector/node_modules/sapnwrfc/out/Release/sapnwrfc.node',
     '/root/SAPConnector/node_modules/sapnwrfc/Release/sapnwrfc.node',
     '/root/SAPConnector/node_modules/sapnwrfc/build/default/sapnwrfc.node',
     '/root/SAPConnector/node_modules/sapnwrfc/compiled/0.12/linux/x64/sapnwrfc.node' ] }
error a precompiled module could not be found or loaded
info trying to compile it...
make: Entering directory `/root/SAPConnector/node_modules/sapnwrfc/build'
  CXX(target) Release/obj.target/sapnwrfc/src/binding.o
/root/.node-gyp/0.12.7/deps/v8/include/v8.h: In function âstd::string convertToString(const v8::Handle<v8::Value>&)â:
/root/.node-gyp/0.12.7/deps/v8/include/v8.h:816: error: âv8::HandleScope::HandleScope()â is protected
../src/Common.h:41: error: within this context
/root/.node-gyp/0.12.7/deps/v8/include/v8.h: In function âstd::string convertToString(const SAP_UC*)â:
/root/.node-gyp/0.12.7/deps/v8/include/v8.h:816: error: âv8::HandleScope::HandleScope()â is protected
../src/Common.h:55: error: within this context
../src/Common.h:56: error: âNewâ is not a member of âv8::Stringâ
/root/.node-gyp/0.12.7/deps/v8/include/v8.h: In function âv8::Handle<v8::Value> RfcError(const RFC_ERROR_INFO&)â:
/root/.node-gyp/0.12.7/deps/v8/include/v8.h:816: error: âv8::HandleScope::HandleScope()â is protected
../src/Common.h:82: error: within this context
../src/Common.h:84: error: âNewâ is not a member of âv8::Stringâ
../src/Common.h:87: error: âNewâ is not a member of âv8::Stringâ

-------------

**Comment by agebert** [comment]
This is probably related to node version 0.12.x which is not source compatible to node 0.10.x. At the moment you have to go back to node 0.10.x or port the code. My plan is to port it to the upcoming unified node 4.0.

**Comment by StefanScherer** [comment]
Seems that the latest commit in master branch is able to build inside a Linux Docker container.

**Comment by jikku** [comment]
Thanks for all the responses folks.
