### ISSUE TITLE
Collaboration?

### ISSUE THREAD

**Issue by bsrdjan** [jdorner/node-sapnwrfc#15]
I am the author of another open source node rfc connector and wonder if we could evenrually join forces and collaborate somehow? If sounds interesting my pm is in my gh profile.

**Comment by stefanschererseal** [comment]
+1 !!

**Comment by stefanschererseal** [comment]
@bsrdjan @jdorner any update on this?

**Comment by bsrdjan** [comment]
got no response from @jdorner
