### ISSUE TITLE
Time Out method

### ISSUE THREAD

**Issue by madhusudhanvenkatesan** [jdorner/node-sapnwrfc#17]
Hi, I am trying to extend time out on my node application for SAP using this Module, but i couldnt find any. Can you expose Timeout function?

**Comment by jdorner** [comment]
As far as I can see there is no way to change the timeout value for RFC calls from outside SAP.
To get around this, you could to set the profile parameter rdisp/max_wprun_time of this server to a higher value. But this would affect all dialog processes - which might be a bad idea. 
Another way would be to periodically call COMMIT WORK inside your function module which effectively resets the timeout counter. But this is also a bad solution which might have really bad side effects when you are not just reading from database.

**Comment by NilsFrkal** [comment]
Joachim Dorner is right. We looked at external timeout as part of our service patterns. We had to make some fairly big enhancements to enable the consumer to provide the timeout time from outside and you will have to enable idempotency etc. If this is critical for your business please let me know. I can get you in touch with the guy who did it for us. Cheers, Nils

**Comment by madhusudhanvenkatesan** [comment]
Thanks jdorner & NilsFrkal for your reply. 
Sorry i couldnt check my emails i was OOO. 
In SAP we have increased timeout but our SAPNWRFC is getting timeout in 2 mins. It is a critical business for us. It would be helpful if you can let me know what needs to be done.
