### ISSUE TITLE
Unable to install sapnwrfc on Ubuntu 16.04

### ISSUE THREAD

**Issue by eshikafe** [jdorner/node-sapnwrfc#32]
austin@analytics:~$ npm install sapnwrfc

> sapnwrfc@0.2.0 install /home/austin/node_modules/sapnwrfc
> node preinstall.js

{ Error: Could not locate the bindings file. Tried:
 → /home/austin/node_modules/sapnwrfc/build/sapnwrfc.node
 → /home/austin/node_modules/sapnwrfc/build/Debug/sapnwrfc.node
 → /home/austin/node_modules/sapnwrfc/build/Release/sapnwrfc.node
 → /home/austin/node_modules/sapnwrfc/out/Debug/sapnwrfc.node
 → /home/austin/node_modules/sapnwrfc/Debug/sapnwrfc.node
 → /home/austin/node_modules/sapnwrfc/out/Release/sapnwrfc.node
 → /home/austin/node_modules/sapnwrfc/Release/sapnwrfc.node
 → /home/austin/node_modules/sapnwrfc/build/default/sapnwrfc.node
 → /home/austin/node_modules/sapnwrfc/compiled/6.9/linux/x64/sapnwrfc.node
    at bindings (/home/austin/node_modules/bindings/bindings.js:88:9)
    at ChildProcess.rebuild (/home/austin/node_modules/sapnwrfc/preinstall.js:25:39)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
  tries:
   [ '/home/austin/node_modules/sapnwrfc/build/sapnwrfc.node',
     '/home/austin/node_modules/sapnwrfc/build/Debug/sapnwrfc.node',
     '/home/austin/node_modules/sapnwrfc/build/Release/sapnwrfc.node',
     '/home/austin/node_modules/sapnwrfc/out/Debug/sapnwrfc.node',
     '/home/austin/node_modules/sapnwrfc/Debug/sapnwrfc.node',
     '/home/austin/node_modules/sapnwrfc/out/Release/sapnwrfc.node',
     '/home/austin/node_modules/sapnwrfc/Release/sapnwrfc.node',
     '/home/austin/node_modules/sapnwrfc/build/default/sapnwrfc.node',
     '/home/austin/node_modules/sapnwrfc/compiled/6.9/linux/x64/sapnwrfc.node' ] }
error a precompiled module could not be found or loaded
info trying to compile it...
make: Entering directory '/home/austin/node_modules/sapnwrfc/build'
  CXX(target) Release/obj.target/sapnwrfc/src/binding.o
  CXX(target) Release/obj.target/sapnwrfc/src/Connection.o
  CXX(target) Release/obj.target/sapnwrfc/src/Function.o
../src/Function.cc: In static member function ‘static v8::Localv8::Value Function::NewInstance(Connection&, Nan::NAN_METHOD_ARGS_TYPE)’:
../src/Function.cc:59:60: warning: ‘v8::Localv8::Object v8::Function::NewInstance() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::Localv8::Object func = Nan::New(ctor)->NewInstance();
                                                            ^
In file included from /home/austin/.node-gyp/6.9.1/include/node/v8.h:25:0,
                 from ../src/Common.h:28,
                 from ../src/Function.h:28,
                 from ../src/Function.cc:25:
/home/austin/.node-gyp/6.9.1/include/node/v8.h:3274:52: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                    ^
/home/austin/.node-gyp/6.9.1/include/node/v8config.h:333:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/Function.cc: In member function ‘v8::Localv8::Value Function::IntToExternal(CHND, const SAP_UC_, v8::Localv8::Value)’:
../src/Function.cc:656:37: warning: ‘v8::Localv8::Int32 v8::Value::ToInt32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   RFC_INT rfcValue = value->ToInt32()->Value();
                                     ^
In file included from ../src/Common.h:28:0,
                 from ../src/Function.h:28,
                 from ../src/Function.cc:25:
/home/austin/.node-gyp/6.9.1/include/node/v8.h:8202:14: note: declared here
 Local<Int32> Value::ToInt32() const {
              ^
../src/Function.cc: In member function ‘v8::Localv8::Value Function::Int1ToExternal(CHND, const SAP_UC_, v8::Localv8::Value)’:
../src/Function.cc:675:43: warning: ‘v8::Localv8::Int32 v8::Value::ToInt32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   int32_t convertedValue = value->ToInt32()->Value();
                                           ^
In file included from ../src/Common.h:28:0,
                 from ../src/Function.h:28,
                 from ../src/Function.cc:25:
/home/austin/.node-gyp/6.9.1/include/node/v8.h:8202:14: note: declared here
 Local<Int32> Value::ToInt32() const {
              ^
../src/Function.cc: In member function ‘v8::Localv8::Value Function::Int2ToExternal(CHND, const SAP_UC_, v8::Localv8::Value)’:
../src/Function.cc:699:43: warning: ‘v8::Localv8::Int32 v8::Value::ToInt32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   int32_t convertedValue = value->ToInt32()->Value();
                                           ^
In file included from ../src/Common.h:28:0,
                 from ../src/Function.h:28,
                 from ../src/Function.cc:25:
/home/austin/.node-gyp/6.9.1/include/node/v8.h:8202:14: note: declared here
 Local<Int32> Value::ToInt32() const {
              ^
../src/Function.cc: In member function ‘v8::Localv8::Value Function::FloatToExternal(CHND, const SAP_UC_, v8::Localv8::Value)’:
../src/Function.cc:722:40: warning: ‘v8::Localv8::Number v8::Value::ToNumber() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   RFC_FLOAT rfcValue = value->ToNumber()->Value();
                                        ^
In file included from ../src/Common.h:28:0,
                 from ../src/Function.h:28,
                 from ../src/Function.cc:25:
/home/austin/.node-gyp/6.9.1/include/node/v8.h:8166:15: note: declared here
 Local<Number> Value::ToNumber() const {
               ^
../src/Function.cc: In member function ‘v8::Localv8::Value Function::BCDToInternal(CHND, const SAP_UC*)’:
../src/Function.cc:1198:39: warning: ‘v8::Localv8::Number v8::Value::ToNumber() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   return scope.Escape(value->ToNumber());
                                       ^
In file included from ../src/Common.h:28:0,
                 from ../src/Function.h:28,
                 from ../src/Function.cc:25:
/home/austin/.node-gyp/6.9.1/include/node/v8.h:8166:15: note: declared here
 Local<Number> Value::ToNumber() const {
               ^
  SOLINK(target) Release/obj.target/sapnwrfc.node
  COPY Release/sapnwrfc.node
make: Leaving directory '/home/austin/node_modules/sapnwrfc/build'
/home/austin
`-- sapnwrfc@0.2.0

npm WARN enoent ENOENT: no such file or directory, open '/home/austin/package.json'
npm WARN austin No description
npm WARN austin No repository field.
npm WARN austin No README data
npm WARN austin No license field.
austin@analytics:~$

austin@analytics:~$ node -v
v6.9.1
austin@analytics:~$ npm -v
3.10.8

**Comment by eshikafe** [comment]
Issue has been resolved after I downgraded to node 4.2.6 and npm 3.5.2

austin@analytics:~$ npm install sapnwrfc

> sapnwrfc@0.2.0 install /home/austin/node_modules/sapnwrfc
> node preinstall.js

ok found precompiled module at /home/austin/node_modules/sapnwrfc/compiled/4.2/linux/x64/sapnwrfc.node
/home/austin
`-- sapnwrfc@0.2.0
  +-- bindings@1.2.1
`-- nan@2.4.0

npm WARN enoent ENOENT: no such file or directory, open '/home/austin/package.json'
npm WARN austin No description
npm WARN austin No repository field.
npm WARN austin No README data
npm WARN austin No license field.

austin@analytics:~$ node

> var r = require('sapnwrfc');
> undefined

**Comment by StefanScherer** [comment]
But we should provide new precompiled versions for 4.6 LTS and 6.9 LTS.
